app = "poker-cli"
primary_region = "lhr"

[[services]]
  auto_start_machines = true
  auto_stop_machines = true
  internal_port = 3000
  min_machines_running = 1
  protocol = "tcp"

  [[services.ports]]
    port = 31337

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
