# fly.toml app configuration file for alexa-icy-bush-8494 on 2025-02-14
#
# See https://fly.io/docs/reference/configuration/ for more details.
#

app = "poker-cli"
primary_region = "lhr"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 8080

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
